# Setup environment for Docker
language: generic
services: docker
dist: trusty
notifications:
  email: false

# Environment setup before test script. Runs for each build
before_install:

  # Get Image from hub
  - docker pull $DOCKER_IMG

  # Set permissions for Docker mount
  - sudo chgrp -hR 1000 $CNG_HOST_PATH 

# The test script for each build
script:
  - docker run --privileged --sysctl net.ipv6.conf.all.disable_ipv6=0 -v $CNG_HOST_PATH:/home/user/contiki-ng -ti $DOCKER_IMG bash --login -c "make -C tests/??-$TEST_NAME";
  # Check outcome of the test
  - $CNG_HOST_PATH/contiki-ng/tests/check-test.sh $CNG_HOST_PATH/tests/??-$TEST_NAME; exit $?;

# Environment variables
env:
  # Global environment variables, i.e., set for all builds
  global:
    - DOCKER_IMG='contiker/contiki-ng'
    - CNG_HOST_PATH=`pwd`
  # Each line in the 'matrix' triggers a separate Travis build
  matrix:
    - TEST_NAME='compile'
